server:
  port: 8085
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 119.45.248.45:8848
    gateway:
      discovery:
        locator:
          enabled: true
    loadbalancer:
      retry:
        enabled: true
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password: 123