server:
  port: 8087
spring:
  application:
    name: service
  cloud:
    nacos:
      server-addr: 119.45.248.45:8848
  datasource:
    url: jdbc:mysql://119.45.248.45:3306/soil?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1310
    type: com.alibaba.druid.pool.DruidDataSource